image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - npm install
    - npm run build
    - cd dist
    - echo "//${CI_SERVER_HOST}/api/v4/projects/28807495/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - cat .npmrc
    - npm publish